### ISSUE TITLE
Runtime error on special Phoenix.Endpoint usage

### ISSUE THREAD

**Issue by simonprev** [mtrudel/bandit#100]
Hello! I tried to replace Cowboy with Bandit in a Phoenix app that uses Absinthe as a GraphQL implementation for our server.
I tried to debug it locally but the error raises _sometimes_ and it’s always linked to our `/graphql` endpoint.

Here is our special Phoenix.Endpoint usage: We use different plug that halt the connexion before it reaches Phoenix.Router.

```elixir
  # ...
  plug(Plug.MethodOverride)
  plug(Plug.Head)

  plug(MyAppHealth.Router)
  plug(MyAppGraphQL.Router)
  plug(:halt_if_sent)
  plug(MyAppWeb.Router)

  # Splitting routers in separate modules has a negative side effect:
  # Phoenix.Router does not check the Plug.Conn state and tries to match the
  # route even if it was already handled/sent by another router.
  defp halt_if_sent(%{state: :sent, halted: false} = conn, _opts), do: halt(conn)
  defp halt_if_sent(conn, _opts), do: conn
```

It does not always "crash" but it seems to be linked to telemetry events. It does not impact the user request. Here is the runtime error:

```elixir
[mfa=Phoenix.Logger.phoenix_endpoint_start/4 ] [info] POST /graphql
[mfa=Phoenix.Logger.phoenix_endpoint_stop/4 ] [info] Sent 400 in 157µs
[mfa=Phoenix.Logger.phoenix_endpoint_start/4 ] [info] POST /graphql
[mfa=Phoenix.Logger.phoenix_endpoint_stop/4 ] [info] Sent 400 in 166µs
[mfa=Phoenix.Logger.phoenix_endpoint_start/4 ] [info] POST /graphql
[mfa=Phoenix.Logger.phoenix_endpoint_stop/4 ] [info] Sent 400 in 166µs
[mfa=Phoenix.Logger.phoenix_endpoint_start/4 ] [info] POST /graphql
[mfa=Phoenix.Logger.phoenix_endpoint_stop/4 ] [info] Sent 400 in 157µs
[mfa=MyAppGraphQL.Plugs.ErrorReporting.report_message/1 ] [error] [absinthe_resolution_error: [%{"message" => "No query document supplied"}]]
[mfa=:gen_server.error_info/8 ] [error] GenServer #PID<0.1896.0> terminating
** (FunctionClauseError) no function clause matching in Bandit.HTTP1.Handler.handle_info/2
    (bandit 0.6.9) lib/thousand_island/handler.ex:5: Bandit.HTTP1.Handler.handle_info({#Reference<0.2692061718.3879796743.144965>, :ok}, {%ThousandIsland.Socket{socket: #Port<0.55>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 15000, span: %ThousandIsland.Telemetry{span_name: :connection, span_id: "5IBONXXLYJSSSC2Y", start_time: -576460732887533691}}, %{handler_module: Bandit.HTTP1.Handler, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {MyAppWeb.Endpoint, []}}}})
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.2692061718.3879796743.144965>, :ok}
State: {%ThousandIsland.Socket{socket: #Port<0.55>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 15000, span: %ThousandIsland.Telemetry{span_name: :connection, span_id: "5IBONXXLYJSSSC2Y", start_time: -576460732887533691}}, %{handler_module: Bandit.HTTP1.Handler, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {MyAppWeb.Endpoint, []}}}}
```

The error never happens on normal Phoenix.Router defined routes.

**Comment by mtrudel** [comment]
Yep. Looks like you have a process sending a message (`{#Reference<0.2692061718.3879796743.144965>, :ok}`) to the underlying HTTP handler process. This isn't generally a supported thing (the Plug API doesn't give us any way to expose such messages up to the application, and because of the way that the underlying server works there's no other easy way for your application to be notified of them). 

Is this a new error (since 0.6.9)? I don't see offhand where this would be coming from telemetry, at least within our implementation, but it's brand new so it's always a possibility. I might also suspect that it is something our telemetry calls in your code; what telemetry events are you hooking, and what's the implementation on your side of them?

**Comment by simonprev** [comment]
I don’t know if it’s new, what version would you like me to try on?

> what telemetry events are you hooking, and what's the implementation on your side of them

I’m attaching handlers for `phoenix.router_dispatch.stop.duration` in my code, do you think it can be linked? I’ll try again but with my telemetry handlers disabled 👍

**Comment by mtrudel** [comment]
I would try with Bandit 0.6.8 if you could, just to ensure it's nothing related to *our* recent telemetry additions (the event you mention is emitted by phoenix itself, so I'm doubtful, but want to be sure). 

I suspect that you'll continue to see the errors occurring even on 0.6.8, at which point we can confidently start looking at what it is specifically that your telemetry handlers are doing. Is it possible to share them here?

**Comment by simonprev** [comment]
I’m using [TelemetryUI](https://hexdocs.pm/telemetry_ui/readme.html#features) to attach handlers. You can see the code here: https://github.com/mirego/telemetry_ui/blob/v2.0.1/lib/telemetry_ui/reporter.ex#L20

**Comment by mtrudel** [comment]
Closing as there's nothing for us to do here.
