### ISSUE TITLE
Error when using graphql-ws protocol

### ISSUE THREAD

**Issue by maxsalven** [mtrudel/bandit#102]
I'm trying to use Bandit with an application that uses the graphql-ws protocol:
https://github.com/wodup/absinthe_graphql_ws

The protocol allows for sending connection params (e.g. a token), and the server can close the socket if e.g. the token is invalid:
https://github.com/wodup/absinthe_graphql_ws/blob/main/lib/absinthe/graphql_ws/transport.ex#L129

However I get this error when using Bandit. With a regular Phoenix/cowboy setup, this error does not occur.
```
** (FunctionClauseError) no function clause matching in Bandit.WebSocket.Connection.do_deflate/3
    (bandit 0.6.9) lib/bandit/websocket/connection.ex:236: Bandit.WebSocket.Connection.do_deflate({:close, 4403, "Forbidden"}, %ThousandIsland.Socket{socket: #Port<0.139>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, span: %ThousandIsland.Telemetry{span_name: :connection, span_id: "XJGNI6FEZC4RZZ22", start_time: -576460747475728060}}, %Bandit.WebSocket.Connection{websock: WodUpWeb.GraphqlWSSocket, websock_state: %Absinthe.GraphqlWS.Socket{absinthe: %{opts: [context: %{pubsub: WodUpWeb.Endpoint}], pipeline: {Absinthe.GraphqlWS.Socket, :absinthe_pipeline}, schema: WodUpWeb.Graphql.Schema}, connect_info: %{}, endpoint: WodUpWeb.Endpoint, handler: WodUpWeb.GraphqlWSSocket, keepalive: 30000, pubsub: WodUp.PubSub, assigns: %{}, initialized?: false, subscriptions: %{}}, state: :open, compress: nil, fragment_frame: nil, span: %Bandit.Telemetry{span_name: :websocket, span_id: "VO6L3P3TOR4NWFO5", start_time: -576460746978892054}, metrics: %{recv_text_frame_bytes: 131, recv_text_frame_count: 1}})
    (bandit 0.6.9) lib/bandit/websocket/handler.ex:42: anonymous fn/3 in Bandit.WebSocket.Handler.handle_data/3
```

Here's the relevant code from the reference JS implementation of graphql-ws if that helps:
https://github.com/enisdenjo/graphql-ws/blob/799cfc7bbe0f6d1a5c90b4880f02c58c5c3a06d4/src/server.ts#L612-L614

https://github.com/enisdenjo/graphql-ws/blob/799cfc7bbe0f6d1a5c90b4880f02c58c5c3a06d4/src/__tests__/server.ts#L437-L458

**Comment by moogle19** [comment]
Hi @maxsalven ,
currently Bandit doesn't support custom closing messages via the `websock` callbacks.

I just landed a PR to add support similar to Cowboy.

**Comment by mtrudel** [comment]
Strictly speaking, the implementation of `Absinthe.GraphqlWS.{Socket,Transport}` returns invalid tuples at https://github.com/wodup/absinthe_graphql_ws/blob/main/lib/absinthe/graphql_ws/transport.ex#L205; nothing in the `Phoenix.Socket.Transport` contract indicates explicit support for close tuples, and they have worked on Cowboy to date only by happy accident. 

The work at https://github.com/phoenixframework/websock/pull/6 et al will be adding explicit support for this, and will land in Bandit as #99. I'll be landing the PR stack for this later today, and will reference back to this PR.

**Comment by mtrudel** [comment]
@moogle19 where is the PR for Cowboy support that you mention? I don't see any recent work on Cowboy or plug_cowboy for this, or am I misunderstanding your comment?

**Comment by moogle19** [comment]
@mtrudel 
I was referring to #103 which adds support for the `cowboy`-like `{:reply, {:close, close_code, message}, state}` in continuations.

**Comment by mtrudel** [comment]
The work to support custom code codes (required for this to work as expected) just landed in Bandit, and is defined in WebSock 0.5 (also released). If there are any follow-on issues required, feel free to open another issue here!

**Comment by maxsalven** [comment]
Sorry to bring up an old issue, but I'm still seeing errors here


```
** (FunctionClauseError) no function clause matching in Bandit.WebSocket.Connection.do_deflate/3
```

```
lib/bandit/websocket/connection.ex:261 Bandit.WebSocket.Connection.do_deflate({:close, integer(), "..."}, %ThousandIsland.Socket{...}, %Bandit.WebSocket.Connection{...})
```

It looks like we still don't support messages like `{:close, 4403, "Forbidden"}`
https://github.com/mtrudel/bandit/blob/19e9b74e277ff9bf4e331b0b08082a1e718ea764/lib/bandit/websocket/connection.ex#L268

This is far from my area of competency, but I think that is required to meet the `graphql-ws` spec.

**Comment by mtrudel** [comment]
@maxsalven, what are you returning from your websock? The spec doesn't allow you to explicitly send `:close` frames yourself; we do it for you as a side effect of you returning one of the tuples that starts with `:stop`. From the looks of what you're sending it would seem that perhaps you're trying to send a close frame yourself?

**Comment by mtrudel** [comment]
Actually, looking at this more closely, Bandit is working as designed. You're (presumably) trying to send `:close` tuples via the `:push`/`:reply` form, which is not supported by the either the [WebSock spec](https://hexdocs.pm/websock/WebSock.html#t:message/0) or (accordingly) by Bandit. If you want to close the connection, you need to return one of the stop tuples defined in WebSock's [`handle_result` type](https://hexdocs.pm/websock/WebSock.html#t:message/0)
