### ISSUE TITLE
Question: Differences between Cowboy and Bandit

### ISSUE THREAD

**Issue by tyhill2** [mtrudel/bandit#104]
Hello. No issue. Just a general question.

What are the differences between Cowboy and Bandit? I understand that Bandit is 100% Elixir.

But if I'm proposing this to my Lead, I'm wanting to show him just what the differences are, all the way down to the most basic level.

Thanks for any info you may have.

**Comment by mtrudel** [comment]
I agree with @gmile's suggestions above! Nothing further to be done here, will close this issue.
