### ISSUE TITLE
Bandit needs a logo

### ISSUE THREAD

**Issue by mtrudel** [mtrudel/bandit#108]
In trying to break from Bandit's unfortunate name origins, I'd prefer for the intent of 'bandit' to be more like 'mischievous
 cute animal' rather than any cowboy / 'wild west' origins. Maybe a cute raccoon with a mask or something?

https://huntsvillebusinessjournal.com/news/2018/10/28/trash-pandas-launch-logo-to-worldwide-acclaim-and-demand/

Feel free to brainstorm / contribute!

**Comment by houllette** [comment]
Here are a few Midjourney generations - went with more of a purple color palette because of Elixir traditionally using a lot of purple. 

Feel free to use or disregard - they were made with the Midjourney subscription tier associated with General Commercial Terms (so they are good to use as you see fit) 🙂 

![bandit1](https://user-images.githubusercontent.com/6202965/228330440-9ca5da22-b702-45dd-bbc0-e07d291d0158.png)
![bandit2](https://user-images.githubusercontent.com/6202965/228330464-7aee9052-f0b3-4de3-b4fb-3f2322a10d19.png)

**Comment by mtrudel** [comment]
Those are wild! I'm going to play around with a couple of prompts myself and see what comes up - I may chime back here with some feedback / further requests for help. Thanks so much!

**Comment by bcardarella** [comment]
The only push back I may provide is I think the legality around protecting the IP of the logo is in question: https://www.garrigues.com/pt/en_GB/garrigues-digital/us-copyright-office-publishes-new-guidelines-registration-ai-generated-works

the US copyright office requires "human authorship", if this project doesn't mind others using the logo then by all means go for it. But if use of the logo is a concern I don't think you have any enforcement options at the moment

**Comment by mtrudel** [comment]
@bcardarella that's a great point; thanks for raising it (this whole contemporary landscape has so many legal subtleties like this that I haven't even thought of. Wild times.)

I think this is a case where I'm not going to let perfect be the enemy of good; being able to source a (frankly amazing looking) logo for ~zero effort is just too compelling. Once Bandit is a worldwide concern then I think we can worry about legal protections on the logo :)

Thanks for the note!

**Comment by mtrudel** [comment]
@houllette do you have any variations on those two above that may spur some ideas? I've tried spinning up a few in both Midjourney and DALL-E and it's..... a lot harder to write a good prompt than I appreciated. Frankly both of the options you dropped above are great, but I'm curious to see if variations are even better.

Personally, I think I like the glossy, vaguely comic book style of the first one!

**Comment by bcardarella** [comment]
If you do use, it may be a good idea to keep a record of what phrase was given to midjourney to produce the image

**Comment by houllette** [comment]
Here are a few variations I liked using the first one as a starting point (I like the third one the most personally); the prompt I used to start the whole thing off wasn't all too complex - `mischievous cute raccoon with bandit mask, cartoon style, flat design, purple`

![bandit3](https://user-images.githubusercontent.com/6202965/228676112-0d1980c4-ee83-4790-93e7-b390a5929f72.png)
![bandit4](https://user-images.githubusercontent.com/6202965/228676137-b4e06fc0-ee84-4897-b9e6-33a0ce7427fe.png)
![bandit5](https://user-images.githubusercontent.com/6202965/228676151-751467b2-754c-43c6-8f89-1396cfdab06b.png)

**Comment by mtrudel** [comment]
I'm *this* close to picking #3 above; the character, shape, everything is just about perfect. 

One crazy idea; what would he look like if he was holding a plug (like an extension cord) and/or a (web)sock?

**Comment by houllette** [comment]
Here are a couple variations that turned out ok, but it's difficult getting it specific with a small object to hold - so things like "extension cord" and "light socket plug" just end up being a mess of wires or a light bulb

![bandit6](https://user-images.githubusercontent.com/6202965/228886687-7602f073-39cc-478c-a67d-7c139aa18a40.png)
![bandit7](https://user-images.githubusercontent.com/6202965/228886775-5195d207-aa44-4adb-b78b-07388928eb0c.png)

**Comment by mtrudel** [comment]
`mischievous cute raccoon with domino mask, holding an extension cord, cartoon style, flat design, purple, comic book style`:

![](https://cdn.discordapp.com/attachments/1091032968086167702/1091049793226297444/mtrudel_mischievous_cute_raccoon_with_domino_mask_holding_an_ex_3825747a-e2a4-47ed-b658-95e325f7d24d.png)

![](https://cdn.discordapp.com/attachments/1091032968086167702/1091050573836582932/mtrudel_mischievous_cute_raccoon_with_domino_mask_holding_an_ex_b14e020a-0a52-4578-bf0c-232546a77ac8.png)

**Comment by mtrudel** [comment]
`mischievous cute raccoon with domino mask, holding a chemisty beaker full of dark purple liquid, cartoon style, flat design`:

![](https://cdn.discordapp.com/attachments/1091032968086167702/1091053979271692350/mtrudel_mischievous_cute_raccoon_with_domino_mask_holding_a_che_1ac3989d-2146-47ba-a92a-792528c5102c.png)

**Comment by mtrudel** [comment]
Option 1:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/79646/228927838-077474a5-9cd7-45fa-bd5d-ec1fadcc0a58.png">

**Comment by mtrudel** [comment]
Option 2:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/79646/228927771-806fd01a-fc9b-4be6-8477-e82a3e4a23e5.png">

**Comment by mtrudel** [comment]
Option 3:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/79646/228927659-143bbcde-22de-4d45-9cdd-3ef260bebc4e.png">

**Comment by mtrudel** [comment]
Option 4:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/79646/228927499-916bc7c5-b651-4689-858b-cfb7f1c9279e.png">

**Comment by mtrudel** [comment]
The votes are in (and I'm, frankly in a bit of a hurry because I want to get stickers made for ElixirConf EU :). Option 3 is the (super cute) winner, and our new mascot!

README and ex_docs have been updated, logo source is in the `assets` folder of the project.

Thanks all for voting, and special thanks to @houllette for being the Midjourney inspiration for all this!
