### ISSUE TITLE
Connection Draining at Shutdown

### ISSUE THREAD

**Issue by mruoss** [mtrudel/bandit#109]
Hey @mtrudel 

I really like Bandit and want to start using it more. Now I've stumbled upon the topic of connection draining. Does something like [Plug.Cowboy.Drainer](https://hexdocs.pm/plug_cowboy/Plug.Cowboy.Drainer.html) exist for Bandit? Or are there plans to add it? Or is it something you'd see outside of the module?

Thanks,
Michael

**Comment by mtrudel** [comment]
Hi Michael!

Connection draining is built in to Thousand Island, the library that sits underneath Bandit. You can read details on the implementation here: https://github.com/mtrudel/thousand_island#connection-draining--shutdown

I'm going to be spending next week adding a bunch of configuration parameters to Bandit/Thousand Island, and some of those parameters will have to do with connection draining. If there's anything specifically you'd like to see, please let me know!

**Comment by mruoss** [comment]
Oh I see. As far as I can tell (running Cowboy without the Drainer), Cowboy has a similar mechanism built in. The Drainer gives the possibility to configure/extend the shutdown timeout, i.e. the time `Handler` processes have to finish the request.
