### ISSUE TITLE
Compress response body

### ISSUE THREAD

**Issue by timothyvanderaerden** [mtrudel/bandit#113]
Within our Phoenix application we set the `compress` option in the endpoint `http` config, [Cowboy](https://hexdocs.pm/plug_cowboy/Plug.Cowboy.html) then tries to compress the response body. Looking through the [Bandit documentation](https://hexdocs.pm/bandit/Bandit.PhoenixAdapter.html) this doesn't seem possible. Are there any plans to add this or is this maybe already possible?

```ex
config :web, Web.Endpoint,
  http: [compress: true]
```

**Comment by mtrudel** [comment]
I had some free time today so I started on this work a bit earlier than planned at #114. It's working great, but still needs a bit of polish. Should be ready in the next couple of days.

**Comment by mtrudel** [comment]
Released as 0.7.2

**Comment by timothyvanderaerden** [comment]
Wow, that was fast! This awesome, will try it asap, thank you!
