### ISSUE TITLE
No way to set `:inet6` option for the TCP transport

### ISSUE THREAD

**Issue by justinludwig** [mtrudel/bandit#130]
Basically same thing as https://github.com/mtrudel/thousand_island/issues/25, but for Bandit -- `Bandit.start_link/1` tries to use ThousandIsland's `transport_options` as a keyword list, even when it contains non-keyword options.

I'm trying to use Bandit with a Phoenix app, and pass `:inet6` as the [`:inet.address_family`](https://www.erlang.org/doc/man/inet.html#type-address_family) option to the underlying socket. This is how I'm trying to configure the Phoenix endpoint:

```
config :admin, AdminWeb.Endpoint,
  adapter: Bandit.PhoenixAdapter,
  https: [
    port: 4040,
    thousand_island_options: [
      transport_options: [
        :inet6,
        cipher_suite: :strong,
        client_renegotiation: false,
        dhfile: "/etc/admin/ssl/dhparam.pem",
        cacertfile: "/etc/admin/ssl/ca.pem",
        certfile: "/etc/admin/ssl/cert.pem",
        keyfile: "/etc/admin/ssl/key.pem"
      ]
    ]
  ]
```

If I remove the `:inet6` option, everything seems to work fine (except, as expected, the listening socket binds only to IPv4 addresses); when I include the `:inet6` option, the following error occurs on startup:

```
** (Mix) Could not start application admin: Admin.Application.start(:normal, []) returned an error: shutdown: failed to start child: AdminWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {AdminWeb.Endpoint, :https}
        ** (EXIT) an exception was raised:
            ** (ArgumentError) expected a keyword list as the second argument, got: [:inet6, {:cipher_suite, :strong}, {:client_renegotiation, false}, {:dhfile, "/etc/admin/ssl/dhparam.pem"}, {:cacertfile, "/etc/admin/ssl/ca.pem"}, {:certfile, "/etc/admin/ssl/cert.pem"}, {:keyfile, "/etc/admin/ssl/key.pem"}]
                (elixir 1.14.4) lib/keyword.ex:995: Keyword.merge/2
                (bandit 0.7.7) lib/bandit.ex:342: Bandit.start_link/1
                (stdlib 4.3) supervisor.erl:414: :supervisor.do_start_child_i/3
                (stdlib 4.3) supervisor.erl:400: :supervisor.do_start_child/2
                (stdlib 4.3) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
                (stdlib 4.3) supervisor.erl:1250: :supervisor.children_map/4
                (stdlib 4.3) supervisor.erl:350: :supervisor.init_children/2
                (stdlib 4.3) gen_server.erl:851: :gen_server.init_it/2
                (stdlib 4.3) gen_server.erl:814: :gen_server.init_it/6
                (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by mtrudel** [comment]
That's a 'proplist' Erlangism, which you can replicate as `inet6: true` (they're the same thing under the hood; see the [proplist docs](https://www.erlang.org/doc/man/proplists.html) for details). 

Alternately, you can specify raw IPv6 addresses to bind to at the top level of bandit config, which may be easier / more explicit for your use case. See the `ip` section of the [option docs](https://hexdocs.pm/bandit/Bandit.html#t:options/0) for details.

**Comment by justinludwig** [comment]
Unfortunately, it looks like the underlying Erlang code doesn't actually use proplists functionality to handle the `:inet.address_family` option. If I change my endpoint configuration to this:

```
config :admin, AdminWeb.Endpoint,
  adapter: Bandit.PhoenixAdapter,
  https: [
    port: 4040,
    thousand_island_options: [
      transport_options: [
        inet6: true,
        cipher_suite: :strong,
        client_renegotiation: false,
        dhfile: "/etc/admin/ssl/dhparam.pem",
        cacertfile: "/etc/admin/ssl/ca.pem",
        certfile: "/etc/admin/ssl/cert.pem",
        keyfile: "/etc/admin/ssl/key.pem"
      ]
    ]
  ]
```

The following error occurs on startup:

```
** (Mix) Could not start application admin: Admin.Application.start(:normal, []) returned an error: shutdown: failed to start child: AdminWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {AdminWeb.Endpoint, :https}
        ** (EXIT) shutdown: failed to start child: :listener
            ** (EXIT) :badarg
```

I put together a PR (#132) with a suggestion for how to propagate irregular socket options like `:inet6` through to ThousandIsland.

**Comment by mtrudel** [comment]
The upstream Plug PR has been merged (see link above). It's unreleased at the moment but you can mix off GitHub if needed (or ask them to cut a point release).

I've fixed the issue in Bandit [directly on main](https://github.com/mtrudel/bandit/commit/43d49c8817b2c2f71bf4149036f5680dae36b02d) and cut 1.0.0-pre.2.
