### ISSUE TITLE
ThousandIsland.Transports.SSL.peer_info/1 ** (MatchError) no match of right hand side value: {:error, :einval}

### ISSUE THREAD

**Issue by kkostov** [mtrudel/bandit#161]
Hi,

On certain occasions, my phoenix app starts to continuously show the following error in the log:

```
pp[4468]: 21:21:08.825 [error] GenServer #PID<0.21539.0> terminating
pp[4468]: ** (MatchError) no match of right hand side value: {:error, :einval}
pp[4468]:     (thousand_island 0.6.7) lib/thousand_island/transports/ssl.ex:124: ThousandIsland.Transports.SSL.peer_info/1
pp[4468]:     (bandit 0.7.7) lib/bandit/http2/connection.ex:353: Bandit.HTTP2.Connection.build_transport_info/1
pp[4468]:     (bandit 0.7.7) lib/bandit/http2/connection.ex:191: Bandit.HTTP2.Connection.handle_frame/3
pp[4468]:     (bandit 0.7.7) lib/bandit/http2/handler.ex:26: anonymous fn/3 in Bandit.HTTP2.Handler.handle_data/3
pp[4468]:     (elixir 1.14.4) lib/stream.ex:1744: Stream.do_unfold/4
pp[4468]:     (elixir 1.14.4) lib/enum.ex:2514: Enum.reduce_while/3
pp[4468]:     (bandit 0.7.7) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
pp[4468]:     (bandit 0.7.7) /app/deps/thousand_island/lib/thousand_island/handler.ex:343: Bandit.DelegatingHandler.handle_info/2
pp[4468]: Last message: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.17282>, :tls_connection, [option_tracker: #PID<0.3206.0>, session_tickets_tracker: :disabled, session_id_tracker: #PID<0.3207.0>]}, [#PID<0.21538.0>, #PID<0.21537.0>]}, <<0, 0, 18, 4, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 4, 0, 32, 0, 0, 0, 5, 0, 0, 64, 0, 0, 0, 4, 8, 0, 0, 0, 0, 0, 0, 79, 0, 1, 0, 0, 55, 1, 5, 0, 0, ...>>}
...
```

I went over the function calls in the stack trace, but I'm not sure how to tackle the error. The specific function raising the match error in thousand_island is:

```elixir
  @impl ThousandIsland.Transport
  @spec getopts(socket(), ThousandIsland.Transport.socket_get_options()) ::
          ThousandIsland.Transport.on_getopts()
  defdelegate getopts(socket, options), to: :ssl
```

I would appreciate any pointers as to what might be going wrong.
Thanks!

**Comment by asakura** [comment]
```
pp[4468]: ** (MatchError) no match of right hand side value: {:error, :einval}
pp[4468]:     (thousand_island 0.6.7) lib/thousand_island/transports/ssl.ex:124: ThousandIsland.Transports.SSL.peer_info/1
pp[4468]:     (bandit 0.7.7) lib/bandit/http2/connection.ex:353: Bandit.HTTP2.Connection.build_transport_info/1
```

It seems that `{:error, :einval}` was passed to `peer_info/1` as an argument and the function wants a socket instead. The socket comes from:

```elixir
defmodule Bandit.HTTP2.Handler do

  def handle_data(data, socket, state) do
    (state.buffer <> data)
    |> Stream.unfold(&Frame.deserialize(&1, state.connection.local_settings.max_frame_size))
    |> Enum.reduce_while({:continue, state}, fn
      {:ok, frame}, {:continue, state} ->
        case Connection.handle_frame(frame, socket, state.connection) do
```

I don't see why it might be corrupted here.

@kkostov could you upgrade to the latest version and see if it still breaks?

BTW @mtrudel `ThousandIsland.Socket.local_info/1` and `ThousandIsland.Socket.peer_info/1` might return an error tuple. Current implementation of `build_transport_info/1` for HTTP 1.1 and HTTP 2.0 doesn't take that into account: 

```elixir
  defp build_transport_info(socket) do
    {ThousandIsland.Socket.secure?(socket), ThousandIsland.Socket.local_info(socket),
     ThousandIsland.Socket.peer_info(socket), ThousandIsland.Socket.telemetry_span(socket)}
  end
```

**Comment by mtrudel** [comment]
> BTW @mtrudel ThousandIsland.Socket.local_info/1 and ThousandIsland.Socket.peer_info/1 might return an error tuple

Yeah it's on my short term list to fix those, thanks to your helpful typespec work!

**Comment by mtrudel** [comment]
> It seems that {:error, :einval} was passed to peer_info/1 as an argument and the function wants a socket instead. The socket comes from:

I don't think that's it - `:ssl.peername(socket)` is the one returning the error tuple (this is the same underlying issue as what you'd pointed out above @asakura). My hunch is that, either due to startup latency or just a short-lived connection, we're trying to process a connection that's already been closed by the client (hence the `:einval`) error code from the ssl app). I suspect that more robust handling of error conditions on `local_info/` and `peer_info/1` will resolve this.

**Comment by mtrudel** [comment]
(However, I suspect strongly that this will just move the error up the stack to somewhere inside Bandit's connection setup logic for HTTP/2, since as @asakura points out we don't yet handle these tuples in Bandit. I'm working on this now and should have a new version out shortly that should resolve these errors).

**Comment by kkostov** [comment]
@mtrudel looks like the issue has been resolved. Thank you!! 🙏

**Comment by mtrudel** [comment]
Lovely! I've already merged the relevant fix so I'll go ahead and close this issue. Thanks again for reporting it!
