### ISSUE TITLE
Invalid port is passed to Plug.Conn in v1.0.0-pre.9 with {:local, "unix_socket"}

### ISSUE THREAD

**Issue by ibarchenkov** [mtrudel/bandit#175]
Hello and thank you for the outstanding server! 🙇

Apparently there is a regression in `bandit v1.0.0-pre.9` and `thousand_island v1.0.0-pre.5` when running a Bandit server on a Unix socket behind a proxy.

`Phoenix.Endpoint` configuration:
```elixir
config :my_app, MyAppWeb.Endpoint,
  http: [ip: {:local, "/tmp/phoenix_endpoint.sock"}, port: 0],
  url: [host: "my-app.example.com", scheme: "https"]
```

The stack trace of the error:
```elixir
** (ArgumentError) errors were found at the given arguments:
  * 1st argument: not an integer
    :erlang.integer_to_binary("/tmp/phoenix_endpoint.sock")
    (plug 1.14.2) lib/plug/conn.ex:1934: Plug.Conn.request_url_port/2
    (plug 1.14.2) lib/plug/conn.ex:1827: Plug.Conn.request_url/1
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/static.ex:98: Phoenix.LiveView.Static.render/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
```

Downgrading `bandit` and `thousand_island` to the previous `pre` versions made the error disappear.
I'm not familiar with the project internals, but willing to contribute a fix if you navigate me to the right place.
Thank you in advance.

**Comment by moogle19** [comment]
The problem seems to be the following code:

https://github.com/mtrudel/bandit/blob/5268c2eb5e8a86c0583b815c9918b829e0a88d88/lib/bandit/pipeline.ex#L67-L90

`determine_host_and_port/4` doesn't check for `{:local, ...}`, `{:unspec, ...}` or `{:undefined, ...}` which are all valid return values for `sockname/1`.
