### ISSUE TITLE
Can't accept :options key in :http section for MyApp.Endpoint

### ISSUE THREAD

**Issue by astorre88** [mtrudel/bandit#181]
After dependency was put to Phoenix app it can't start anymore because of it had :options section in :http options passed to MyApp.Endpoint configuration. It seems naturally to have them as is without a conflicts.

**Comment by mtrudel** [comment]
(I noticed you've closed the issue; is it resolved for you)

Bandit should fully support any option that Phoenix specifies by default in any of their generators. If you've added cowboy specific configuration to your endpoint config, we obviously won't support that without changes, but there should be an equivalent config option in bandit for just about every config option in cowboy.

**Comment by astorre88** [comment]
Got you! Thanks!
