### ISSUE TITLE
GitHub Sponsors?

### ISSUE THREAD

**Issue by Nezteb** [mtrudel/bandit#185]
*cough* https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account *cough*

**Comment by mtrudel** [comment]
Thank you for the kind suggestion (seriously, thank you! It's incredibly humbling to have people ask about this), however sponsorships aren't a thing that I want to explore with my Open Source work. I'm fortunate enough to be a in a position where I'm gainfully employed & have a stable enough work/life balance that I'm able to do the work I love without it being an imposition on my life, and I'm wary of having that change once I start accepting money (even 'no strings attached' sponsorship money) for my OSS work. Not to mention that there are innumerable developers working on awesome stuff that *could* benefit more from the support.

So, while I'm flattered and honoured to be asked about this, it's not something I have the need or inclination to do. Once again though, thank you so much for bringing it up!
