### ISSUE TITLE
Support for SSE

### ISSUE THREAD

**Issue by mohan-win** [mtrudel/bandit#19]
Hi,

Thanks for building a pure elixir HTTP server. Since the library is 100 % http/2 compliant, wondering if it includes the support for Server Side Events ? 

Thanks in advance.

**Comment by mtrudel** [comment]
Hi! 

SSE are not actually part of the HTTP/2 spec (they're actually a w3c recommendation, not an IETF standard). I think you might be thinking of 'push promises' within the HTTP/2 spec, which we *do* support (see Plug.Conn.push/3). 

If you *are* in fact looking for SSE, you can get 99% of the way there by sending a chunked response with a specific MIME type (see https://www.w3.org/TR/2012/WD-eventsource-20120426/ for details), but that's as I'm planning on taking SSE support in Bandit; the required interface for SSE is just too different from Plug to make it worth the maintenance burden.

Also, note that WebSocket support is *this* close to landing in Bandit (see the [0.5 branch](https://github.com/mtrudel/bandit/tree/0.5) for progress). I'm expecting to have end-to-end WebSocket support with Bandit and Phoenix implemented by mid-September 2022. This may be a better answer fro your needs than SSE.

**Comment by mohan-win** [comment]
Thanks for the details, very helpful. Yes, looking forward to the WebSocket end-to-end support with Bandit 🙌🏾
