### ISSUE TITLE
Note on phoenix install

### ISSUE THREAD

**Issue by jamilabreu** [mtrudel/bandit#191]
`adapter: Bandit.PhoenixAdapter,` needs to be added the initial Endpoint config (line 16 of config.ex in clean phoenix install), otherwise it still tries to use Cowboy on start 🙏

**Comment by mtrudel** [comment]
This is already documented in the 'Using Bandit with Phoenix' section of the Bandit hex docs at https://hexdocs.pm/bandit/Bandit.html#module-using-bandit-with-phoenix. Is there some error with the existing documentation that I'm missing or do you have a specific suggestion on how to improve it? Happy to make things clearer for people!

**Comment by jamilabreu** [comment]
For people like me who copy the line without reading 😄  this would be more clear:

```
# config/config.exs

config :everyone, EveryoneWeb.Endpoint,
  adapter: Bandit.PhoenixAdapter, # add this line
  url: [host: "localhost"],
 ```

**Comment by mtrudel** [comment]
Fixed in `main`; this will be out in the next release. Thanks for the issue!

**Comment by jamilabreu** [comment]
🐤 🔥

PS reminder to include in README as well
