### ISSUE TITLE
Logs from  request crash do not follow the configured Logger's format, nor carry over any metadata

### ISSUE THREAD

**Issue by hubertlepicki** [mtrudel/bandit#196]
I am not sure which thing is to blame as I updated a bunch of libraries + switched to Bandit in the same round, but since that I noticed that some of the log lines that I'd expect to be logged as error are not marked as one in our DataDog panel.

We're using Gigalixir, with DataDog attached as syslog drain, so I think the problem is that these log lines are not logged with log level = error:

As you can see, logs from other places in the system are properly logged as errors (maked in red), it's just when the request handler crashes on something like parsing JSON or parsing multipart body (i.e. in Plug.Parsers) that I don't see it as error

![bandit](https://github.com/mtrudel/bandit/assets/33274/6263b60a-d6c5-45ff-b356-d103a47eb95f)

Is there a Bandit configuration I should change or you folks think it's unrelated and I should look for problem elsewhere?

**Comment by mtrudel** [comment]
Bandit intentionally does *very* little logging on its own; along with Thousand Island they both strongly embrace 'let it crash' as a general policy and so most of the logging you *will* see comes from the BEAM logging a Bandit process crash. The stacktrace lines in your logs are coming directly from the BEAM, so configuring the level they're logged at is a VM concern concern and specifically not something that Bandit has any configuration for on its own. 

I'm not entirely sure where to go to change the level that the BEAM logs crashes at (I'd love to learn, though!). Curiously if I crash a process in an iex session the whole things gets logged as error:

<img width="1502" alt="image" src="https://github.com/mtrudel/bandit/assets/79646/dc8b0dea-16d5-4358-88e8-166e4e25027e">

As an aside, this has been a pervasive source of user issues; Cowboy generally silently swallowed errors with no logging of any kind, so when folks switch to Bandit they'll often start seeing crashes and stack traces that have always been there, but never got surfaced.

**Comment by hubertlepicki** [comment]
So what I did was that I created two applications from scratch, Phoenix 1.7.7: one with Cowboy, another one with Bandit. There's nothing in them, just default scaffold of 

```
$ mix phx.new --no-ecto --no-html errors_[cowboy|bandit]
```

and the Bandit app obviously has replaced Cowboy with Bandit according with Readme. Now, let's say I crash the Plug.ParsersJson with this curl command, which sends a broken JSON:

```
$ curl -X POST http://localhost:4000/ \
   -H 'Content-Type: application/json' \
   -d '{"login:"my_login","password":"my_password"}'
```

The behavior on Cowboy is that I get printed an error in *debug* level like this:

```
**[info] POST /
[debug] ** (Plug.Parsers.ParseError) malformed request, a Jason.DecodeError exception was raised with message "unexpected byte at position 9: 0x6D (\"m\")"
    (plug 1.14.2) lib/plug/parsers/json.ex:95: Plug.Parsers.JSON.decode/3
    (plug 1.14.2) lib/plug/parsers.ex:340: Plug.Parsers.reduce/8
    (errors_cowboy 0.1.0) lib/errors_cowboy_web/endpoint.ex:1: ErrorsCowboyWeb.Endpoint.plug_builder_call/2
    (errors_cowboy 0.1.0) deps/plug/lib/plug/debugger.ex:136: ErrorsCowboyWeb.Endpoint."call (overridable 3)"/2
    (errors_cowboy 0.1.0) lib/errors_cowboy_web/endpoint.ex:1: ErrorsCowboyWeb.Endpoint.call/2
    (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.10.0) /home/hubert/Projekty/hubertlepicki/errors_cowboy/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.10.0) /home/hubert/Projekty/hubertlepicki/errors_cowboy/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.10.0) /home/hubert/Projekty/hubertlepicki/errors_cowboy/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
**
```


On Bandit, I get the same + repeated the same message with log_level = :error:

```
[info] POST /
[debug] ** (Plug.Parsers.ParseError) malformed request, a Jason.DecodeError exception was raised with message "unexpected byte at position 9: 0x6D (\"m\")"
    (plug 1.14.2) lib/plug/parsers/json.ex:95: Plug.Parsers.JSON.decode/3
    (plug 1.14.2) lib/plug/parsers.ex:340: Plug.Parsers.reduce/8
    (errors_bandit 0.1.0) lib/errors_bandit_web/endpoint.ex:1: ErrorsBanditWeb.Endpoint.plug_builder_call/2
    (errors_bandit 0.1.0) deps/plug/lib/plug/debugger.ex:136: ErrorsBanditWeb.Endpoint."call (overridable 3)"/2
    (errors_bandit 0.1.0) lib/errors_bandit_web/endpoint.ex:1: ErrorsBanditWeb.Endpoint.call/2
    (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.0.0-pre.10) lib/bandit/pipeline.ex:116: Bandit.Pipeline.call_plug/2
    (bandit 1.0.0-pre.10) lib/bandit/pipeline.ex:22: Bandit.Pipeline.run/6
    (bandit 1.0.0-pre.10) lib/bandit/http1/handler.ex:31: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.0.0-pre.10) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.0.0-pre.10) /home/hubert/Projekty/hubertlepicki/errors_bandit/deps/thousand_island/lib/thousand_island/handler.ex:399: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

[error] GenServer #PID<0.701.0> terminating
** (Plug.Parsers.ParseError) malformed request, a Jason.DecodeError exception was raised with message "unexpected byte at position 9: 0x6D (\"m\")"
    (plug 1.14.2) lib/plug/parsers/json.ex:95: Plug.Parsers.JSON.decode/3
    (plug 1.14.2) lib/plug/parsers.ex:340: Plug.Parsers.reduce/8
    (errors_bandit 0.1.0) lib/errors_bandit_web/endpoint.ex:1: ErrorsBanditWeb.Endpoint.plug_builder_call/2
    (errors_bandit 0.1.0) deps/plug/lib/plug/debugger.ex:136: ErrorsBanditWeb.Endpoint."call (overridable 3)"/2
    (errors_bandit 0.1.0) lib/errors_bandit_web/endpoint.ex:1: ErrorsBanditWeb.Endpoint.call/2
    (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.0.0-pre.10) lib/bandit/pipeline.ex:116: Bandit.Pipeline.call_plug/2
    (bandit 1.0.0-pre.10) lib/bandit/pipeline.ex:22: Bandit.Pipeline.run/6
    (bandit 1.0.0-pre.10) lib/bandit/http1/handler.ex:31: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.0.0-pre.10) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.0.0-pre.10) /home/hubert/Projekty/hubertlepicki/errors_bandit/deps/thousand_island/lib/thousand_island/handler.ex:399: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.11>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.2307709195.431489030.153875>, start_time: -576460748161934911, start_metadata: %{parent_telemetry_span_context: #Reference<0.2307709195.431489025.154755>, remote_address: {127, 0, 0, 1}, remote_port: 45260, telemetry_span_context: #Reference<0.2307709195.431489030.153875>}}}, %{handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true, opts: %{http_1: [], http_2: [], websocket: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {ErrorsBanditWeb.Endpoint, []}}, websocket_enabled: true}}
```

So there is a difference indeed, b/c in production the debug error is filtered out, and I think because Bandit/ThousandIslands use proper OTP primitives the logger picks up a GenServer crash and reports on it. This is great and indeed is precisely what you describe @mtrudel b/c we will get more crashes logged that were silently swallowed before.

What I think my problem is, that these logs do not follow the configured format, in my case:

```
 config :logger, :console,                                                                                                                                                                                                                                                                                                                        
    format: "$time $metadata[$level] $message\n",  
```

which I think is the default. So the crash *is logged*, and indeed people will see more errors after switching to Bandit, but they're not going to be alerted by them by something that ingests and parses logs, because the level (and other metadata) are missing.

What would be *super cool* is that when Bandit request crashes, on something like parsing JSON or multipart/form data requests, we do get logs that not only use the correct :error level, but also follow the format and retain metadata that may have been set by some Plugs in the pipeline that executed successfully before reaching the crashing parsers.

I wonder if you think that's possible to achieve, and if so - maybe can point me towards what configuration - or code changes need to be done, I could take a shot at implementing this as a feature because, to be fair, the lack of proper logging when something like crashes from early Plugs has been bothering me for years.

**Comment by mtrudel** [comment]
@hubertlepicki did you find any success with setting logging levels in the BEAM directly? I'd love to have a consistent story to tell folks that bring this up

**Comment by hubertlepicki** [comment]
@mtrudel actually the log levels *and format* are correct. The problem are in my case the multi-line log statements that are logged, with no span/tracing info attached and DataDog cannot figure it out.

If you look at the screenshot you provided you can see that only the first line has the formatter-provided timestamp and [error] level, the rest of the report is underneath. There are several ways to fix this:

- you can write a custom Console Logger formatter that would split the log multi-line log messages and format each line separately
- you can use this custom logger formatter, that follows Heroku's log format that does precisely that  https://hex.pm/packages/logfmt_ex

but we decided to switch to the structured logging using JSON and this library https://github.com/Nebo15/logger_json

So far this is running fine on staging, but I consider the issue resolved as I can see the nicely formatted logs being detected as Errors in DataDog.

This issue can remain closed as it turned out that it didn't have any fault on the Bandit side.
