### ISSUE TITLE
chunk calls ignore send errors

### ISSUE THREAD

**Issue by ausimian** [mtrudel/bandit#214]
https://github.com/mtrudel/bandit/blob/b27d4416fe2aed37b4baff2cd95fe680f56a8427/lib/bandit/http1/adapter.ex#L468C34-L469

It looks like, at least for the http1 adapter (and maybe for the http2 adapter also), `chunk/2` calls ignore errors from the socket layer. I found this testing some streaming code which I was testing with `curl`. The streaming itself all worked fine, but if terminated `curl` there was no way for my plug to discover this since `chunk/2` _always_ returns `:ok`. Since, in this case, the intention is to keep streaming until the client terminates, this leaves upstream processes running for some period of time (possibly indefinitely)

**Comment by ausimian** [comment]
Sorry I don't think that was super clear. The scenario is a long running stream of text actually being sourced from elsewhere (the 'upstream'), delivered via `chunk/2` to a client. It is the client that determines when the stream finishes, simply by closing the socket. 

Bandit ignores any socket errors in its adapter, so it's impossible to determine that chunk/2 failed, which results in the upstream machinery hanging around.

Fwiw, Cowboy does appear to detect the socket errors.

**Comment by mtrudel** [comment]
This is a bit of a tricky one since the `chunk/2` contract doesn't return an updated conn (there's an option for it, but the docs suggest that servers return just `:ok`). 

Agreed that we can do a better job of surfacing this error back to the calling plug, but the calling plug is going to have to be on the hook for doing the right thing in an error case.

I'll get this work queued up in the next week or so and have it out in the next `pre` release.

**Comment by ausimian** [comment]
Thx, appreciate it Matt.

Out of interest, where does the complexity actually come from? The adapter spec allows for chunk/2 to return an error tuple. The bug, from my reading of the code, at least for http1, is that bandit explicitly ignores the result of TI’s send call and always returns ok.

**Comment by mtrudel** [comment]
> Out of interest, where does the complexity actually come from? The adapter spec allows for chunk/2 to return an error tuple. The bug, from my reading of the code, at least for http1, is that bandit explicitly ignores the result of TI’s send call and always returns ok.

That's exactly it.
