### ISSUE TITLE
Chunked HTTP1 response piped gets interrupted

### ISSUE THREAD

**Issue by jschaeff** [mtrudel/bandit#237]
Hello,

I use Plug.Conn.Chunk to send output from an external program to the client.
When the clients (let's say wget, curl or httpie) writes the data to a file, it works all nicely.

But when the client pipes the output to another program there a strange behaviors:

- Bandit 1.0.0-pre.16
    - on the Plug side, I see a premature end of connection  ` [error] Connection closed`
    - on the client side, the response is incomplete

- Bandit 1.0.0-pre.15
    - on the Plug side, the response is transmitted in chunks integraly without error
    - on the client side, the response is incomplete, and I have a broken pipe error

So I guess there is some improvement between pre.15 and pre.16 because we catch the error, but still there seems to be something wring in the Plug.Conn handling.

a verbose wget does not help much.  Can I increase bandit logs ?

My use case is not easy to reproduce, it depends a lot of my data. But I can be reactive and help out by trying fixes.

**Comment by mtrudel** [comment]
My first hunch is client error; there's nothing different to the server between the two cases (other than perhaps different timing), and I can't immediately see how the client's disposition of the response would affect anything.

The only changes between 15 and 16 that might affect chunked encoding are specifically to do with empty chunk encoding over HTTP/2, which is a pretty specific (though not impossible) case for you to be hitting. Some questions:

* Are you 100% certain that the version difference makes a difference and it isn't just coincidental?
* Is this local, or over the internet? How variable is the client/server connection?
* Do you know if you're using http/2 as a transport? (also helpful: are you using https?)
* If you're able to, running `ThousandIsland.Logger.attach(:trace)` should yield a boatload of logs (beware: they contain everything sent over the wire to Bandit, so anything sensitive will be in there too). Those would be helpful if you could isolate them to around one of the failures.

**Comment by jschaeff** [comment]
I worked on reproducing the issue, but I wasn't able to ... so strange.
Let's close the issue and I'll reopen it if necessary.

Thank you for your responses and support.
