### ISSUE TITLE
How to make bandit serve static assets using http2

### ISSUE THREAD

**Issue by formoxyz** [mtrudel/bandit#25]
Hello,

Thank you for making bandit. I am trying to create a simple server using Plug and wanted to serve static assets like js, css etc using http2.

Please advise how to do that.

I have this is my router (not using phoenix)
plug(Plug.Static,
    at: "/",
    from: :simple,
    gzip: false,
    only: ~w(assets fonts images favicon.ico robots.txt)
  ) 

Thank you

**Comment by mtrudel** [comment]
That's on the Plug side of the Plug API, and not something that's specific to Bandit. At first glance that looks correct from the examples at https://hexdocs.pm/plug/Plug.Static.html, but I'm not able to provide a whole lot more specific help than that (this is a venue for issues with Bandit specifically, not help with using or configuring Plug applications). I might suggest asking on the Elixir Forum for further assistance. I'd also include a complete copy of your router file, as the limited snippet above isn't terribly helpful in helping to diagnose the issue. Good luck!
