### ISSUE TITLE
Quic support

### ISSUE THREAD

**Issue by sleipnir** [mtrudel/bandit#28]
I would like to know if the Quic protocol support is in your roadmap

References:
https://pt.wikipedia.org/wiki/QUIC
https://github.com/emqx/quic

**Comment by mtrudel** [comment]
It's 100% on the roadmap, but not until post 1.0. Per the roadmap on the README I've got a few things to handle before then (finishing up WebSocket support, improving telemetry, tightening up documentation). 

QUIC is actually going to be a big (fun!) workup, as it is UDP based and will therefore require a buildup all the way from the datagram layer. I'm really looking forward to it!

**Comment by sleipnir** [comment]
Awesome. Thanks!
