### ISSUE TITLE
UDS Support

### ISSUE THREAD

**Issue by sleipnir** [mtrudel/bandit#29]
Would it be possible to use Bandit over Unix Domain Sockets? If yes, could you provide an example?

**Comment by mtrudel** [comment]
As promised, here's how to start Bandit on a Unix domain socket:

```elixir
  Bandit.start_link(
    plug: MyPlug,
    options: [transport_options: [ip: {:local, "/path/to/socket"}], port: 0]
  )
```

As noted in the [Thousand Island docs](https://hexdocs.pm/thousand_island/ThousandIsland.Transports.TCP.html#content), the socket is not removed after the server shuts down.

**Comment by sleipnir** [comment]
Thanks @mtrudel great!

**Comment by mtrudel** [comment]
Renamed the issue to make it more searchable by future folks
