### ISSUE TITLE
Content-Length header gets overridden

### ISSUE THREAD

**Issue by danschultzer** [mtrudel/bandit#338]
Is there a good reason for why `content-length` header gets overridden/removed?

https://github.com/mtrudel/bandit/blob/4f15f029e7aa17f8e7f98d55b0e94c684dee0971/lib/bandit/adapter.ex#L128
https://github.com/mtrudel/bandit/blob/4f15f029e7aa17f8e7f98d55b0e94c684dee0971/lib/bandit/headers.ex#L93

I'm mocking AWS streaming response where there first request is a `HEAD` request to get the `content-length`. There should be no body for `HEAD` request but the `content-length` should be whatever it was set to. There could be a conditional to check the method, but I'm not sure Bandit should modify the content-length at all if it has already been set?

**Comment by danschultzer** [comment]
Oh I get it now. The body is not returned for `HEAD` request as expected. I assume the body is necessary to set to calculate the right length depending on the compression?

**Comment by danschultzer** [comment]
Ok, I figured out the issue I had. My HTTP client was accepting gzip, Bandit responded accordingly. Setting `http_options: [compress: false]]` makes this work like AWS. All good 😄

**Comment by mtrudel** [comment]
I actually have a few things on the backlog to refine this behaviour (mostly stemming from [this issue](https://github.com/mtrudel/bandit/issues/306#issuecomment-1946378120)).

* If a `content-length` header is set when a user called `send_chunked/2`, just send a non transfer-encoded response body out as bare bytes as the user calls `chunk/2` (this is already what we do for HTTP/2, which doesn't do transfer-encoding)
* I have to verify that we're doing the right thing with sending a content-length header for HEAD/304 (where we MAY send it) and 204 (where we MUST NOT send it)
