### ISSUE TITLE
Clearing process dictionary breaks on some keys

### ISSUE THREAD

**Issue by chrismccord** [mtrudel/bandit#350]
ref: https://github.com/phoenixframework/phoenix/issues/5807

**Comment by ryanwinchester** [comment]
The error is from the `to_string/1` on the key which can be `term`, and it's getting a tuple.

https://github.com/mtrudel/bandit/blob/bb159d47a9a6c4d213d42f78d6600a471e21c7b9/lib/bandit/http1/handler.ex#L37

**Comment by mtrudel** [comment]
Oh dang. Patching this directly.
