### ISSUE TITLE
Performance Cowboy 2 vs Bandit Phoenix adapter

### ISSUE THREAD

**Issue by svsool** [mtrudel/bandit#372]
👋 Hello Mat!

I did a quick load test on an MBP M1 (elixir 1.14.0-otp-25 / erlang 25.0.4) with one Erlang scheduler online (+S = 1 in VM args) using [k6](https://k6.io/), and wanted to share some results.

TL;DR: RPS seems to be lower (18k vs 23k) with Bandit vs Cowboy 2.7 and http 1.1.

Phoenix with Cowboy Adapter (2 x runs)

![image](https://github.com/mtrudel/bandit/assets/1452141/961394a4-daaa-4399-af0f-01593fe5e12d)

![image](https://github.com/mtrudel/bandit/assets/1452141/5b8bb9e7-1859-4563-86fa-e2683b6c72ee)

Phoenix with Bandit Adapter (2 x runs)

![image](https://github.com/mtrudel/bandit/assets/1452141/b6112926-1829-4ba6-a2cf-52f9bdebe6bc)

![image](https://github.com/mtrudel/bandit/assets/1452141/efbef221-891f-42d7-963a-f07be914d7be)

Steps to reproduce:
- download original setup (generated using `mix phx.new <app_name> --adapter <cowboy | bandit>` + logging disabled and production release compiled)
  - [phx_cowboy_test.zip](https://github.com/user-attachments/files/15905178/phx_cowboy_test.zip)
  - [phx_bandit_test.zip](https://github.com/user-attachments/files/15905176/phx_bandit_test.zip)
- run `MIX_ENV=prod mix do deps.get, compile, release`
- run `PHX_SERVER=true SECRET_KEY_BASE=random PORT=4000 _build/prod/rel/<app_name>/bin/<app_name> start`
- install [k6](https://k6.io/) and run `k6 run echo.test.js`
  - test can be found [here](https://gist.github.com/svsool/c9d60f4e45e5a0b243ffd1f7d597ace9)

I also tried setups from this [repo](https://gitlab.com/stressgrid/dummies) (related [post](https://stressgrid.com/blog/webserver_benchmark/)) except response modified to match original test, sleep removed and number of schedulers set to 1. 

A bare Cowboy 1.x setup gave 40k+ RPS on a single core using the same [echo test](https://gist.github.com/svsool/c9d60f4e45e5a0b243ffd1f7d597ace9).

![image](https://github.com/mtrudel/bandit/assets/1452141/2b6c8017-2854-4bda-b9b6-03f82dd7ff39)

And with Cowboy 2.7 from that same [repo](https://gitlab.com/stressgrid/dummies).

![image](https://github.com/mtrudel/bandit/assets/1452141/049dd0e6-d3df-4c89-a98b-f986bc4398b9)

With Bandit 1.5 + Plug 1.16, no Phoenix ([bandit_test.zip](https://github.com/user-attachments/files/15905667/bandit_test.zip))

![image](https://github.com/mtrudel/bandit/assets/1452141/8b5122fa-7293-48c6-801f-f44942d6a9c0)

Also tried to run Bandit's own [benchmarks](https://github.com/mtrudel/benchmark) locally using `mix benchmark cowboy bandit@main`, but unfortunately got the following error:

<img src="https://github.com/mtrudel/bandit/assets/1452141/48367d0c-4a48-4472-bc4f-c2232c44af07" width="400" />

Let me know if additional tweaking required to achieve better results with Bandit vs Cowboy and whether results are relatively comparable when reproduced using your hardware.

Thanks!

**Comment by svsool** [comment]
Did re-run tests with latest elixir 1.17.1-otp-27 / erlang 27.0, and with the same synthetic test Bandit performs slightly better than Cowboy 2.7 with http 1.1 when used as Phoenix adapter, and better than Cowboy 2.7 with a standalone setup.

Seems Cowboy 1.x performs worse with the latest Elixir / Erlang build that with elixir 1.14.0-otp-25 / erlang 25.0.4.

Phoenix with Cowboy Adapter

![image](https://github.com/mtrudel/bandit/assets/1452141/876b1041-a94a-4afa-aade-cfee9194bade)

![image](https://github.com/mtrudel/bandit/assets/1452141/b588bab5-ac87-46ea-a4ee-929938cd34c1)

Phoenix with Bandit Adapter

![image](https://github.com/mtrudel/bandit/assets/1452141/45c3de86-8987-4d85-9aec-8b9774c16e4c)

![image](https://github.com/mtrudel/bandit/assets/1452141/50b9cf0b-4a18-4da9-ac7d-4f066609b609)

With Bandit 1.5 + Plug 1.16, no Phoenix

![image](https://github.com/mtrudel/bandit/assets/1452141/1b6b2e6c-9e9f-45dc-97e7-41c52b2ccdb6)

![image](https://github.com/mtrudel/bandit/assets/1452141/28374c27-48a8-4988-b016-b10c52b3c861)

With Cowboy 1.x

![image](https://github.com/mtrudel/bandit/assets/1452141/3cd40159-6682-46cf-a278-b0a5160822be)

![image](https://github.com/mtrudel/bandit/assets/1452141/adb36ed4-2db4-4e38-b0ae-9b776cd497e5)

With Cowboy 2.7

![image](https://github.com/mtrudel/bandit/assets/1452141/84101b20-f85f-400d-8a4c-73de55cd0039)

![image](https://github.com/mtrudel/bandit/assets/1452141/6557d56b-11cf-4fac-93fd-5bdbe1d794ac)

**Comment by svsool** [comment]
Feel free to re-open if going to re-test and compare relative numbers yourself or if there are any other possible improvements. 👋

**Comment by mtrudel** [comment]
Thanks for the report! I'd not seen k6 before but it looks like exactly the client-side tool I'd wanted access to when I wrote the benchmark library (the client implementation there is pretty sad). What do you think would be involved in moving the mtrudel/benchmark suite over to use k6 on the client side?

**Comment by svsool** [comment]
hi @mtrudel, k6 from my experience is relatively easy to setup, and there are [examples](https://medium.com/@monish.correia/integrating-k6-load-testing-with-github-actions-a-comprehensive-guide-4437a7c8145a) on running it with github actions (see related [k6-action](https://github.com/grafana/k6-action)), what comes to test cases which bandit benchmark suit requires you'd probably know the details the best.
