### ISSUE TITLE
(Bandit.HTTPError) Request line HTTP error

### ISSUE THREAD

**Issue by stocks29** [mtrudel/bandit#407]
In my phoenix app which uses Bandit, I'm using bling to process stripe webhooks and the stripe cli to forward webhooks to my local server. 

Some of the webhook requests fail but some are successful. Here are the errors I'm seeing:

```
[info] Sent 200 in 11ms
[error] ** (Bandit.HTTPError) Request line HTTP error: "{\n"
[info] POST /webhooks/stripe
[info] Sent 200 in 3ms
[error] ** (Bandit.HTTPError) Request line HTTP error: " \"description\": \"Subscription creation\",\n"
[info] POST /webhooks/stripe
[info] Sent 200 in 8ms
[error] ** (Bandit.HTTPError) Request line HTTP error: "ll,\n"
[info] POST /webhooks/stripe
[info] Sent 200 in 370µs
[error] ** (Bandit.HTTPError) Request line HTTP error: " null,\n"
```

I switched from Bandit to cowboy and the errors are no longer occurring. I'm not sure what the problem is, but it seems to be specific to Bandit.

**Comment by mtrudel** [comment]
You're almost certainly dropping a `conn` rebind somewhere; check out the background in https://github.com/mtrudel/bandit/issues/361.

**Comment by stocks29** [comment]
Thanks @mtrudel, I'll take a look at the bling library and see if there is a conn rebind missing somewhere.

**Comment by mtrudel** [comment]
Closing for hygeine due to likely resolution. If the issue persists, feel free to reopen.
