### ISSUE TITLE
Wrong content length with keepalive leads to unexpected output

### ISSUE THREAD

**Issue by treere** [mtrudel/bandit#414]
Hi, I am using bandit and for some reason the client was sending me a wrong content length.

The scenario is bandit, http1.1 in a keepalive connection.

I have apost with the wrong content length followed by a get.

I have written this test the shows the problem.  (`test/bandit/http1/request_test.exs`)
```
    test "if content length is wrong return error", context do
      client = SimpleHTTP1Client.tcp_client(context)

      SimpleHTTP1Client.send(client, "POST", "/echo_method", [
        "host: localhost",
        "content-length: 101"
      ])

      Transport.send(
        client,
        1..100 |> Enum.map(fn _ -> "a" end) |> Enum.join("")
      )

      assert {:ok, "200 OK", _headers, "POST"} = SimpleHTTP1Client.recv_reply(client)

      SimpleHTTP1Client.send(client, "GET", "/echo_method", ["host: banana"])
            assert {
               :ok,
               "200 OK",
               _headers,
               "ET"
             } = SimpleHTTP1Client.recv_reply(client)
    end
```

I think that something is wrong here. I am not sure if it is a problem of the test suite but trying the same calls in a toy project the result is different: error on 1st call and 200 on the second

**Comment by mtrudel** [comment]
This is intrinsic to the protocol. Requests within an HTTP connection are framed via one of `content-length`, `transfer-encoding`, or a closure of the underlying transport. If the framing information is incorrect (as it is in your example), there's nothing for the other end to do; there's no way to recover a valid framing of the connection. 

Without knowing what your server side is doing, it must be said that if your Plug doesn't read the request body, then Bandit does so after your Plug.call completes (it does so [here](https://github.com/mtrudel/bandit/blob/main/lib/bandit/http1/socket.ex)). So it's safe to say that the request body would be read (or, in this case, attempted to be read) before the server would be able to handle the following GET. 

From the information you've provided, it would seem that Bandit is doing the best it can here. If you still believe there to be an error here, please provide more detail as to the specifics. From what I can see here we're doing things correctly.

**Comment by treere** [comment]
Thanks a lot for the explanation! 
I understand the situation and agree that there's nothing to be done. 

I'll go ahead and close the issue. Thanks again for your time and help!
