### ISSUE TITLE
WSS broken by frame masking

### ISSUE THREAD

**Issue by peaceful-james** [mtrudel/bandit#422]
![image](https://github.com/user-attachments/assets/db3f35cb-40f2-4477-a812-0ecbaf6aa69d)

Maybe this is just happening for me. I am investigating.

**Comment by peaceful-james** [comment]
I confirm problem goes away when I run on commit `cd855ec`.

**Comment by mtrudel** [comment]
Thanks for the note. I'll back out that addition to give @alisinabh a chance to address it

**Comment by peaceful-james** [comment]
> Thanks for the note. I'll back out that addition to give @alisinabh a chance to address it

Wait, I am blaming the wrong PR. It works fine on commit `898afdc`.

**Comment by peaceful-james** [comment]
OK I confirm the problem is on commit `f16b4c3` which is PR #421 which is yours @mtrudel 

The call is coming **from inside the house**

**Comment by mtrudel** [comment]
Can you provide a repro?

**Comment by alisinabh** [comment]
I took a quick look and it seems like we responding with compression enabled (`content-encoding: gzip`) on websocket which is not supported for websocket (it is but permessage-deflate must be used).

### Working version
<img width="727" alt="Screenshot 2024-11-18 at 11 32 07 AM" src="https://github.com/user-attachments/assets/01243bb1-50fd-41be-a57b-75dc5ad0cbb6">

### Not working version
<img width="737" alt="Screenshot 2024-11-18 at 11 32 26 AM" src="https://github.com/user-attachments/assets/681e4dcd-e04a-4f74-8d45-b47e49dd0c37">

**Comment by mtrudel** [comment]
Got it! I backed that PR out of main/1.6.0 and re-released. I'll get this fixed directly. 

Since this is no longer an issue on main I'll copy the relevant details from here over to #421 (which I'll also reopen). 

Thanks for the quick bug @peaceful-james !

**Comment by peaceful-james** [comment]
@mtrudel I used 1.6.1. No issues! 👍🏻 I confirm that my "concerns are still fixed in it".
