### ISSUE TITLE
Broken link to perf test, on github project ReadMe page

### ISSUE THREAD

**Issue by mpettibone** [mtrudel/bandit#436]
On the main bandit GitHub readme [page](https://github.com/mtrudel/bandit), the link to the [performance test](https://github.com/mtrudel/bandit/actions/runs/4449308920) is broken.

Quote (from ReadMe):

_In [ongoing automated performance tests](https://github.com/mtrudel/bandit/actions/runs/4449308920), Bandit's ..._

**Comment by mtrudel** [comment]
Yep, those performance tests are done via GitHub actions, and only live for 90 (or maybe it's 120) days until GitHub actions expires them out. I should probably just update this to a footnote that explains how to look the most recent one up.

**Comment by mtrudel** [comment]
Thanks for the note!

**Comment by mtrudel** [comment]
README updated!
