### ISSUE TITLE
Gzip compression

### ISSUE THREAD

**Issue by kotsius** [mtrudel/bandit#50]
In anticipation of [v0.7 support for gzip](https://elixirforum.com/t/phoenix-1-7-0-rc-0-is-out/51625/41) compression, may I suggest that it is implemented in a way that goes one step further than Cowboy. Instead of a binary on/off option, Bandit could allow the user to set the gzip compression level, like Nginx and [Caddy](https://caddyserver.com) do, as follows for Phoenix:

config :prj, Endpoint, http(s): [gzip: 0-9]

The default :gzip value would be zero (no compression). There would be no pre-selected compression level, and that is a good thing. Nginx's default seems to be 1, Caddy's 6. The Bandit documentation could recommend a positive value or range (e.g. 3 or 1-6), but leave the actual decision to the user. In the future, there could also be other options, such as:

config :prj, Endpoint, http(s): [zstd: 0-22]

In case of conflict, e.g. http(s): [gzip: 2, zstd: 4], the obvious resolution would be to default to gzip.

I hope this helps.

**Comment by moogle19** [comment]
Since http compression only compresses the body and seems to be the same between http 1 & 2 couldn't we implement compression as a Plug without modifying the server?

I played around a bit with it yesterday and it seemed to work without problems (https://github.com/moogle19/plug_compression).

But your suggestion to make the compression configurable sounds good either way.

**Comment by mtrudel** [comment]
@kotsius absolutely! The goal for 0.7 is twofold: first, add a couple of missing things around the project (like compression), and second, make a lot more (non-policy) things configurable. You can expect to see (these are my rough internal notes):

* Compression in HTTP/1 (and 2?)
* WebSockets over H2?
* Upgrade to h2c via `Upgrade` header
* Configurable limits on reading (header count/length, uri / body / frame sizes etc)
* Enhance configuration
  * Add support for defining permitted protocols / upgrades
  * Add support for connection level recv timeouts in TI
  * Add support for changing HTTP2 config values
  * Add Plug.SSL based support for TLS1.3
  * Add easy levers for cert config?
  * Add config point to show packets sent / received (via telemetry)
  * Add config to shutdown delay (TI todo)
  * Add config to WS compression level / direction / global disable (also benchmark this to see if it’s slower. It seems it is)
  * Add support for max_frame_size on WS
  * Explore max size limits for H1 & H2
* Overall readme and docs

In terms of implementation, I agree that a Plug based approach for this *should* be possible. I'm thinking about refactoring the Plug pipelines within the HTTP/1 and H2 implementations to use a common pipeline, which would make things like this really easy. The main difficulty with it is the semantic differences between the two protocols surrounding transfer encoding abstractions. We'll see how it goes.
