### ISSUE TITLE
`Socket.close/1` called with nil

### ISSUE THREAD

**Issue by moogle19** [mtrudel/bandit#54]
After running Greenbone OpenVAS (Vulnerability Scanner) against a bandit server, I noticed this error:

<img width="910" alt="Screenshot 2022-11-17 at 13 45 02" src="https://user-images.githubusercontent.com/792046/202450237-f989a6b5-e81e-429d-9270-2e9fd92d6bae.png">

I don't know the http request which lead to that error and couldn't quite figure out, what request leads to `Socket.close/1` be called with a `nil` value.

@mtrudel Do you have any idea?

**Comment by mtrudel** [comment]
I think what's happening is that the connection is being closed in the very brief interval between when Thousand Island transfers the connection over to the GenServer Handler and when that GenServer knows what its socket is (ie: in the window between when https://github.com/mtrudel/thousand_island/blob/feb400137ad4876b30bc29695579ff8217928a4f/lib/thousand_island/connection.ex#L29 is called to transfer connection ownership to the new process and https://github.com/mtrudel/thousand_island/blob/feb400137ad4876b30bc29695579ff8217928a4f/lib/thousand_island/handler.ex#L301 is called to be informed about the socket). `controlling_process/2` takes care of transferring any messages over to the new mailbox (per https://www.erlang.org/doc/man/gen_tcp.html#controlling_process-2), but there's nothing to prevent the process from being terminated in that window

The solution is to add a `nil` match to `ThousandIsland.Handler.terminate/2`; I'll get that wired up, though it's too racy to be testable I think.

Good catch!

**Comment by mtrudel** [comment]
Fixed in Thousand Island `0.5.12`. Bandit `main` has an updated dependency on it if you want to validate this doesn't occur any longer (assuming it was reproducible-ish)
