### ISSUE TITLE
[warning] Could not determine a protocol

### ISSUE THREAD

**Issue by kotsius** [mtrudel/bandit#81]
I see a lot of "[warning] Could not determine a protocol" messages, often in quick succession, when accessing my Phoenix dev server over HTTP. As it stands, this warning is rather _noisy_. It would be great if it could be a little more informative, or else removed altogether.

Elixir 1.14.3
Phoenix 1.7.0-rc.2
Windows 10

**Comment by mtrudel** [comment]
Upon reflection, the possible marginal benefit of this log line isn't worth the support burden (you're far from the first person to ask about this message, and I'm sure you won't be the last). 

I'll remove this log line entirely in the next release, coming out in the next few days.

Thanks for the note!

**Comment by kotsius** [comment]
For the record, I am using (the Chromium-based) Vivaldi 5.6.2867.58.

Thanks.

**Comment by mtrudel** [comment]
Fixed in https://github.com/mtrudel/bandit/commit/202646b1b38ebbe07a688d4f66174a4754c799f8
